services:
  flask:
    build: ./app/
    container_name: windy-weasel
    command: sh -c "python3 ./app.py"
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

  database:
    build: ./database/
    container_name: gusty-gorilla
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 3