services:
  flask:
    image: ghcr.io/wi22b-projekt-mit-anwendungsentwicklung/windy-weasel:latest
    container_name: windy-weasel
#    volumes:
#      - /Users/lukasschick/Documents/ghcnd_all:/data
#      - /path/to/local/ghcn_all:/data
    command: sh -c "pytest Tests/ && python3 ./app.py"
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  mysql:
    image: ghcr.io/wi22b-projekt-mit-anwendungsentwicklung/gusty-gorilla:latest
    container_name: gusty-gorilla
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mysql_data:
    driver: local