name: Build Docker Images and push to GHCR

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Docker Images and push to GHCR
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout the files
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      # Build and push App Docker image
      - name: Build App Docker image and push
        id: docker_build_flask
        uses: docker/build-push-action@v6
        with:
          context: ./App
          push: true
          file: ./App/Dockerfile
          tags: ghcr.io/wi22b-projekt-mit-anwendungsentwicklung/windy-weasel:latest

      # Build and push Database Docker image
      - name: Build Database Docker image and push
        id: docker_build_database
        uses: docker/build-push-action@v6
        with:
          context: ./Database
          push: true
          file: ./Database/Dockerfile
          tags: ghcr.io/wi22b-projekt-mit-anwendungsentwicklung/gusty-gorilla:latest
